name: GetLatestTag

on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.GetLatestTag.outputs.tag }}
    inputs:
      environment:
        type: string
        required: true
      repository:
        type: string
        required: true
      ref_name:
        type: string
        required: true

jobs:
  GetLatestTag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref_name }}
          fetch-depth: 0

      - name: Print values
        run: |
          echo environment = ${{ inputs.environment }} / branch = ${{ github.ref_name }} / current_tag = $(git describe --tag)

      - name: Get latest tag
        run: |
          if '${{ inputs.environment == 'PROD' && github.ref_name == 'main' }}'
          then
            echo "TAG=$(git describe --tag)" >> $GITHUB_ENV
          elif '${{ inputs.environment == 'STG' && (startsWith(github.ref_name, 'hotfix/') || startsWith(github.ref_name, 'release/')) }}'
          then
            echo "TAG=$(git describe --match "$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-rc*" --abbrev=0 --tags $(git rev-list --tags --max-count=1))"  >> $GITHUB_ENV
          else
            echo ""
          fi

      - name: Print latest tag
        run: |
          echo TAG = ${{ env.TAG }}
